### ISSUE TITLE
tesseract trained file issue

### ISSUE THREAD

**Issue by JunsuKimSustainment** [LinYiHsin/recg_drawing#1]
Thank you for providing awesome module that is able to extract attributes of drawings. 
I really like this and try to re-produce meaningful result. 
During this process I encountered an error that seems to be due to tesseract trained files including 'eng_math', 'eng_gdt', ... 
If you don't mind would you update the repo so that it can contain those files?

Thank you in advance!

**Comment by LinYiHsin** [comment]
Hello, I have already updated several trained files of Tesseract-OCR into the 'tessdata' folder. Simply place them in the 'tessdata' folder located within the installation directory of Tesseract-OCR (the default path would be at C:\Program Files\Tesseract-OCR\tessdata).

Thank you for your response, and I hope this information is helpful to you. If you have any further questions, please don't hesitate to let me know.

Thank you!

**Comment by medhanshrath-t** [comment]
> Thank you for providing awesome module that is able to extract attributes of drawings. I really like this and try to re-produce meaningful result. During this process I encountered an error that seems to be due to tesseract trained files including 'eng_math', 'eng_gdt', ... If you don't mind would you update the repo so that it can contain those files?
> 
> Thank you in advance!

Hey, were you able to get it up and running?
