### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by medhanshrath-t** [LinYiHsin/recg_drawing#2]
Hello, I am trying to recreate your results, but I am not very familiar with Celery. When I run the 3 terminals I am getting a blank page with Hello Root printed on it. Could you help me a bit with this?

**Comment by medhanshrath-t** [comment]
I am also having some trouble with the SQL Server and am getting this error:

`Exception: <class 'sqlalchemy.exc.ProgrammingError'>(['(pyodbc.ProgrammingError) (\'42S02\', "[42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name \'worker_task\'. (208) (SQLExecDirectW)")'])`

I have created a blank SQL Server, I think the problem is related to that.

**Comment by LinYiHsin** [comment]
Hello, 
About the first question, that should be the webpage I used for testing, and the file is located at app\templates\hello_world.html. The actual main page is accessible at http://xxx.xxx.xxx.xxx:443/overview. For the paths to other pages, you can refer to the 'main_blueprint.route' in the app/views.py file.

The second question, do you have a table named 'worker_task' in your database? 
You can execute`python manage.py init_db`in Terminal 3 to get the `DB ready.`.
After that, you can run `python manage.py runserver` to see if it works.

Hope it helps you!

**Comment by medhanshrath-t** [comment]
Thank you very much! Now I am able to upload images, how can I start the recognition?

I tried this: `http://127.0.0.1:443/api/get_drawing_views/3` and I am getting this reply:
```
{
  "error": "Recognition unfinished."
}
```

![image](https://github.com/LinYiHsin/recg_drawing/assets/144231160/46e696d5-3eb5-4783-9098-7bd8a427a6fe)

When I click on click to relabel image:

![image](https://github.com/LinYiHsin/recg_drawing/assets/144231160/91da92a0-84f6-41bb-9e26-99420586ac20)

Overview:

![image](https://github.com/LinYiHsin/recg_drawing/assets/144231160/6cac8333-8e20-4ed8-aac6-1a00d2260191)

Labelled Images:

![image](https://github.com/LinYiHsin/recg_drawing/assets/144231160/349af9a2-b103-4f3a-b3c6-5c3cafad60c6)

**Comment by LinYiHsin** [comment]
The recognition process will automatically execute upon successful image upload, and there will be a status message at the top of the webpage indicating the current step. When you see the message `Recognize [Uploaded Image Name] Success.` , please refresh the page. Note: The warning message will disappear after a while. After refreshing the page, the successfully recognized engineering drawings will be listed on the 'Overview' page. You can click on an image to view the recognition results for that particular engineering drawing.

Your situation appears to involve an error during the recognition process, which resulted in incomplete recognition. I've updated a portion of the error-handling code for you to try. 'UploadFiles/example_dwg.pdf' is an engineering drawing that I successfully tested. You can use it for testing purposes.

Hope it helps you!
If you have any further questions, please don't hesitate to let me know.
